version: '3'
        
networks:
  phyrem_net:
    driver: bridge

services:

  backend:
    container_name: phyrem-backend
    restart: always
    build: .
    ports:
      - "5000:5000"
    networks:
      phyrem_net:
        aliases:
          - phyrem-backend

  # redoc:
  #   image: redocly/redoc
  #   container_name: phyrem-docs
  #   restart: always
  #   ports:
  #     - "3001:80"
  #   environment:
  #     - SPEC_URL=http://localhost:5000/api-docs.json
  #   networks:
  #     phyrem_net:
  #       aliases:
  #         - phyrem-docs

    
